app:
  jwt-secret: { secret }
  jwt-expiration-ms: 36000000
  data-loader: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: {username}
    password: {password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    username: { mail }