server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: task-master
  devtools:
    restart:
      enabled: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
